# Generated by Django 2.2.24 on 2021-08-10 09:31

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_active',
        ),
        migrations.AddField(
            model_name='location',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
