# Generated by Django 5.1.15 on 2026-07-17 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="The broader location this belongs to, e.g. a TOWN's parent PROVINCE. Used to derive `region` for display/grouping.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='django_trips.location'),
        ),
    ]
