# Generated by Django 5.2.16 on 2026-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Uploaded poster photo for destination cards. Takes priority over poster_url when both are set.', null=True, upload_to='locations/posters/'),
        ),
        migrations.AddField(
            model_name='location',
            name='poster_url',
            field=models.URLField(blank=True, help_text="External poster photo URL, used when poster_image isn't uploaded.", null=True),
        ),
    ]
