# Generated by Django 5.1.15 on 2026-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trip',
            name='django_trip_is_feat_a005e5_idx',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='trip',
            name='featured',
            field=models.CharField(blank=True, choices=[('BESTSELLER', 'Bestseller'), ('POPULAR', 'Popular'), ('TOP_RATED', 'Top Rated'), ('TRENDING', 'Trending'), ('NEW', 'New')], help_text='Promotional badge shown on the trip (e.g. Bestseller, Popular); left blank if not featured', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['featured'], name='django_trip_feature_2bfc18_idx'),
        ),
    ]
