# Generated by Django 2.2.24 on 2021-08-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0002_auto_20210810_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_departure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_destination',
            field=models.BooleanField(default=False),
        ),
    ]
