# Generated by Django 5.1.15 on 2026-07-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0002_location_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreview',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Reviewer's home location, e.g. for display as 'Lahore' alongside their review.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_reviews', to='django_trips.location'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Only verified testimonials should be shown publicly.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this testimonial should be shown publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text="Where the person is from, e.g. 'Lahore'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='django_trips.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
