# Generated by Django 2.2.24 on 2021-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0003_auto_20210810_0940'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['slug'], name='django_trip_slug_a2c8a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_slug_for_location'),
        ),
    ]
