# Generated by Django 5.1.15 on 2026-07-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0002_remove_trip_django_trip_is_feat_a005e5_idx_and_more'),
        ('django_trips', '0003_tripreview_location_testimonial'),
    ]

    operations = [
    ]
