# Generated by Django 5.2.16 on 2026-07-31 05:35

import django_trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0003_tripschedule_child_price_pickup_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationpolicy',
            name='refund_schedule',
            field=models.JSONField(blank=True, default=django_trips.models.default_refund_schedule, help_text="Ordered refund tiers, each a {'label', 'min_hours_before_departure', 'refund_percent'} dict, backing the cancellation-policy timeline UI."),
        ),
        migrations.AddField(
            model_name='host',
            name='refund_schedule',
            field=models.JSONField(blank=True, default=list, help_text='Host-level override for the structured refund-tier schedule (same shape as CancellationPolicy.refund_schedule). Empty - the default - falls back to the platform-wide schedule.', null=True),
        ),
    ]
