# Generated by Django 5.2.16 on 2026-07-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0004_cancellationpolicy_refund_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancellationpolicy',
            options={'verbose_name_plural': 'Cancellation policies'},
        ),
    ]
