# Generated by Django 2.2.24 on 2021-08-30 19:46

from django.db import migrations, models
import django.db.models.deletion
import django_trips.mixins


class Migration(migrations.Migration):

    replaces = [('django_trips', '0005_auto_20210825_0951'), ('django_trips', '0006_auto_20210825_1751'), ('django_trips', '0007_auto_20210825_2020'), ('django_trips', '0008_auto_20210825_2026'), ('django_trips', '0009_auto_20210829_0826'), ('django_trips', '0010_auto_20210829_0843'), ('django_trips', '0011_auto_20210829_0844'), ('django_trips', '0012_auto_20210829_0911'), ('django_trips', '0013_auto_20210829_0916'), ('django_trips', '0014_auto_20210829_0932'), ('django_trips', '0015_auto_20210830_1435'), ('django_trips', '0016_auto_20210830_1442'), ('django_trips', '0017_auto_20210830_1922')]

    dependencies = [
        ('django_trips', '0004_auto_20210810_1559_squashed_0009_auto_20210815_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price_bracket',
            field=models.CharField(choices=[('ST', 'Standard'), ('BG', 'Budget'), ('PM', 'Premium')], default='ST', max_length=2),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripschedule',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='host',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='tripavailability',
            name='options',
        ),
        migrations.AddField(
            model_name='tripavailability',
            name='_options',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_destination', to='django_trips.Location'),
        ),
        migrations.RemoveField(
            model_name='host',
            name='cancellation_policy',
        ),
        migrations.AddField(
            model_name='host',
            name='_cancellation_policy',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=85, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            bases=(django_trips.mixins.SlugMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='gear',
        ),
        migrations.AddField(
            model_name='trip',
            name='gear',
            field=models.ManyToManyField(related_name='trip_gear', to='django_trips.Gear'),
        ),
        migrations.RemoveField(
            model_name='tripavailability',
            name='trip',
        ),
        migrations.RenameField(
            model_name='tripavailability',
            old_name='availability',
            new_name='type',
        ),
        migrations.AddField(
            model_name='tripavailability',
            name='trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_availability', to='django_trips.Trip'),
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='schedule',
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_bookings', to='django_trips.Trip'),
        ),
    ]
