# Generated by Django 5.1.15 on 2026-07-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_trips", "0005_tripimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon identifier for frontend rendering (e.g. a lucide icon name)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon identifier for frontend rendering (e.g. a lucide icon name)",
                max_length=50,
            ),
        ),
    ]
