# Generated by Django 5.2.16 on 2026-07-31 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0005_alter_cancellationpolicy_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripOption',
            new_name='TripPackage',
        ),
        migrations.AlterField(
            model_name='trippackage',
            name='name',
            field=models.CharField(
                choices=[
                    ('STANDARD', 'Standard Package'),
                    ('BUDGET', 'Budget Package'),
                    ('PREMIUM', 'Premium Package'),
                ],
                default='STANDARD',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='trippackage',
            name='trip',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='packages',
                to='django_trips.trip',
            ),
        ),
    ]
