# Generated by Django 2.2.24 on 2021-09-06 04:49

import datetime

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('django_trips', '0006_auto_20210831_1640'), ('django_trips', '0007_auto_20210901_1634'), ('django_trips', '0008_auto_20210906_0346'), ('django_trips', '0009_auto_20210906_0405')]

    dependencies = [
        ('django_trips', '0005_auto_20210825_0951_squashed_0017_auto_20210830_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripavailability',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 16, 40, 47, 331647, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripavailability',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripavailability',
            name='is_per_person_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tripschedule',
            name='is_per_person_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name='tripavailability',
            options={'ordering': ['date_to', 'price']},
        ),
        migrations.RenameField(
            model_name='tripbooking',
            old_name='date_from',
            new_name='target_date',
        ),
        migrations.AlterModelOptions(
            name='tripbooking',
            options={'ordering': ('-target_date', '-created_at')},
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
