# Generated by Django 2.2.24 on 2021-08-31 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0005_auto_20210825_0951_squashed_0017_auto_20210830_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripavailability',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 16, 40, 47, 331647, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripavailability',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
