# Generated by Django 2.2.24 on 2021-09-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0006_getting-availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripbooking',
            options={'ordering': ('target_date', '-created_at')},
        ),
    ]
