# Generated by Django 5.2.16 on 2026-08-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0006_rename_tripoption_trippackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Guest agreed to the Terms & Conditions and cancellation policy at booking time'),
        ),
    ]
