# Generated by Django 2.2.24 on 2021-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0007_auto_20210906_0454'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='django_trip_slug_a2c8a8_idx',
        ),
        migrations.AddField(
            model_name='location',
            name='importance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('TW', 'Town'), ('CT', 'City')], default='TW', max_length=2),
        ),
    ]
