# Generated by Django 5.2.16 on 2026-08-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0007_tripbooking_terms_accepted'),
        ('django_trips', '0010_tripbooking_adults_children'),
    ]

    operations = [
    ]
