# Generated by Django 5.2.17 on 2026-08-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0011_tripbooking_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='PUBLISHED', help_text='Editorial state (draft/published) - independent of is_active', max_length=20),
        ),
    ]
