# Generated by Django 5.2.17 on 2026-08-08 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0012_trip_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], max_length=20)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', help_text="Optional context for the change, e.g. 'payment confirmed'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Staff user who made this change; blank means system/automatic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_status_events', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='django_trips.trip')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
