name: Quality

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Pylint:
    runs-on: ubuntu-latest

    name: pylint-python
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: sudo pip install -r requirements.txt

    - name: GitHub Action for pylint
      run: |
        export PYLINTRC=.pylintrc
        sudo python -m run_lint.py
