name: Unit test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7, 3.8, 3.9]
        django-version: ["2.2.27", "3.2.12"]

    name: python-${{ matrix.python-version }},django-${{ matrix.django-version }}
    steps:
    - name: sync directory owner
      run: sudo chown runner:runner -R .*
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        sudo pip install "django==${{ matrix.django-version }}"

    - name: run tests
      run: |
        sudo python -Wd -m pytest -p no:randomly

