name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.11.13, 3.12.10] # https://www.python.org/doc/versions/
        django-version: ["4.2.23"] # https://pypi.org/project/Django/#history

    name: python-${{ matrix.python-version }},django-${{ matrix.django-version }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        sudo pip install -r requirements.txt
        sudo pip install "django==${{ matrix.django-version }}"

    - name: run tests
      run: |
        export PYLINTRC=.pylintrc
        sudo python -m run_lint.py

